# Generated by Django 2.2.5 on 2019-10-02 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='家庭名')),
            ],
            options={
                'verbose_name': '家庭表',
                'verbose_name_plural': '家庭表',
            },
        ),
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('sex', models.CharField(choices=[(0, '男'), (1, '女')], default=1, max_length=1, verbose_name='性别')),
                ('age', models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='年龄')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fpm.Family')),
            ],
            options={
                'verbose_name': '成员表',
                'verbose_name_plural': '成员表',
                'unique_together': {('name', 'family')},
            },
        ),
        migrations.CreateModel(
            name='PerfRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('pre_score', models.SmallIntegerField(default=0, verbose_name='历史分数')),
                ('day_score', models.SmallIntegerField(default=0, verbose_name='今日得分')),
                ('score', models.SmallIntegerField(default=0, verbose_name='记录分数')),
            ],
            options={
                'verbose_name': '绩效记录表',
                'verbose_name_plural': '绩效记录表',
            },
        ),
        migrations.CreateModel(
            name='PerfItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='条目名')),
                ('score_up', models.PositiveSmallIntegerField(default=0, verbose_name='加分')),
                ('score_down', models.SmallIntegerField(default=0, verbose_name='减分')),
                ('description', models.CharField(default='', max_length=256, verbose_name='备注')),
                ('active', models.BooleanField(default=True, verbose_name='状态')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fpm.MemberInfo', verbose_name='成员')),
                ('perf_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fpm.PerfRecord', verbose_name='绩效记录')),
            ],
            options={
                'verbose_name': '绩效项目表',
                'verbose_name_plural': '绩效项目表',
            },
        ),
    ]
