# Generated by Django 2.2.5 on 2019-10-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberinfo',
            name='sex',
            field=models.SmallIntegerField(choices=[(0, '男'), (1, '女')], default=1, max_length=1, verbose_name='性别'),
        ),
    ]
