# Generated by Django 2.2.5 on 2019-10-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpm', '0002_auto_20191002_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfitem',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='备注'),
        ),
    ]
