# Generated by Django 2.2.5 on 2019-10-05 02:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fpm', '0004_auto_20191002_0909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfitem',
            options={'verbose_name': '成员项目表', 'verbose_name_plural': '成员项目表'},
        ),
        migrations.RemoveField(
            model_name='perfitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='perfitem',
            name='perf_record',
        ),
        migrations.RemoveField(
            model_name='perfrecord',
            name='day_score',
        ),
        migrations.RemoveField(
            model_name='perfrecord',
            name='pre_score',
        ),
        migrations.AddField(
            model_name='family',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='mod_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='memberinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberinfo',
            name='mod_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='perfitem',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfitem',
            name='mod_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='perfrecord',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfrecord',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='perfrecord',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fpm.PerfItem', verbose_name='绩效项'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfrecord',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fpm.MemberInfo', verbose_name='成员'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfrecord',
            name='mod_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='perfitem',
            name='name',
            field=models.CharField(max_length=256, verbose_name='项目名'),
        ),
        migrations.AlterField(
            model_name='perfrecord',
            name='score',
            field=models.SmallIntegerField(verbose_name='计分'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mod_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('day', models.DateField(verbose_name='日期')),
                ('score', models.SmallIntegerField(verbose_name='总分')),
                ('score_sum', models.SmallIntegerField(verbose_name='累计分数')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fpm.MemberInfo', verbose_name='成员')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
