# Generated by Django 2.2.5 on 2019-10-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpm', '0005_auto_20191005_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': '成绩表', 'verbose_name_plural': '成绩表'},
        ),
        migrations.AlterField(
            model_name='perfrecord',
            name='day',
            field=models.DateField(verbose_name='日期'),
        ),
    ]
